### ISSUE TITLE
AuditEvents, Status OK but always total 0

### ISSUE THREAD

**Issue by pandalec** [gematik/ref-eRp-FD-Server#14]
Hey! 
Thanks again for the fix, signing with an HBA is now working. I am currently facing the issue that I am not able so get AuditEvents. I always get the following response, doesn't matter what I do with prescriptions of the patient: `{"resourceType":"Bundle","type":"searchset","total":0}`

Any idea what could cause this?
BR
parsi

**Comment by Gematik-Entwicklung** [comment]
Hi @parsifallo,

we have implemented the AuditEvent Resource and Enpoint, but we do not generate any AuditEvent yet. This is planed for one of the future releases.

Best regards,
gemtik Dev-Team.
