### ISSUE TITLE
Keep status of test instance (after restart of application)

### ISSUE THREAD

**Issue by nauni77** [gematik/ref-eRp-FD-Server#17]
Hello,

we use your test intsance with a long running test instance of our system. And it would be much better to keep the state of your system during restart and upgrade. At the moment the already processed eprescriptions are only existing in our system and do not exist in your test instance.

Is there any possibility to keep the status of the old instance during restarting/ upgrading? Is there a database file that can be backuped and used at next start? Or a directory with all neccessary information?

If this exists - do you keep an eye during updates to convert the old eprescription data into a new structure (if needed). That the eld eprescriptions still accessible.

Thanks in advance

Oli

**Comment by Gematik-Entwicklung** [comment]
Hi Oli,

currently we do not persist the data, it is stored in memory only. Persisting the data is planed in a later release. The only way to get the data into the service after a restart is to (re-)create the eprescriptions using the normal interface.

Best regards,
gematik Dev-Team.

**Comment by nauni77** [comment]
Hello,

thanks for that information. At wich month is it planed to implement persisting the data?

Best regards, Oli

**Comment by Gematik-Entwicklung** [comment]
Hi Oli,

we have decided to implement a simple persistance layer to serialize the state of the service to disk. Format of that file will be JSON. Minor format changes in this file will be handled by our service, but we reserve the right to add breaking changes. The implementation of this persistence layer is scheduled within our next sprint, so this should be available in the release end of february.

This simple persistance layer will be replaced with a normal database in a later release, but this does not have priority and therefor we can not say when this will be done. For now this simple solution should solve your problem.

Best regards,
gematik Dev-Team

**Comment by nauni77** [comment]
Hello, this sounds very good. Thanks in advance! Best regards, Oli

**Comment by Gematik-Entwicklung** [comment]
Hi Oli,

we had some time at the end of our current sprint to implement the persistance of the state of the service. You have now the ability to pass a file, the state is read from at startup and written to at shutdown, using the "--state" parameter. If you don't pass the parameter, the state is not stored on disk.

Best regards,
gematik Dev-Team.

**Comment by nauni77** [comment]
Hello, thanks for this option to store the state of your application. I tested it and it worked. Best regards, Oli
