### ISSUE TITLE
server is not running without IPV6 network interface

### ISSUE THREAD

**Issue by nauni77** [gematik/ref-eRp-FD-Server#18]
Hello,

our onprem cluster is not configured for IPV6 and there is no such network interface defined. This cause an error while starting your application:

```
gematik-server-6559dd79b8-xvwwk gematik-server      Running `target/debug/ref-erx-fd-server --enc-key /application/certs/enc_id --enc-cert /application/certs/enc_id.cert --sig-key /application/certs/sig_id --sig-cert /application/certs/sig_id.cert --token 'file:///application/certs/idp_id.pub' --tsl 'https://download.tsl.ti-dienste.de' --bnetza 'file:///application/server/examples/ADJUSTED-BNetzA-VL-seq24.xml'`
gematik-server-6559dd79b8-xvwwk gematik-server 2021-02-03T23:15:09.316955069+01:00 INFO ref_erx_fd_server::tasks::tsl::update - TSL updated: file:///application/server/examples/ADJUSTED-BNetzA-VL-seq24.xml
gematik-server-6559dd79b8-xvwwk gematik-server Error: ServiceError(IoError(Os { code: 97, kind: Other, message: "Address family not supported by protocol" }))
gematik-server-6559dd79b8-xvwwk gematik-server 2021-02-03 23:15:10,325 INFO success: gematik entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
gematik-server-6559dd79b8-xvwwk gematik-server 2021-02-03 23:15:10,326 INFO exited: gematik (exit status 1; not expected)
gematik-server-6559dd79b8-xvwwk gematik-server 2021-02-03 23:15:11,328 INFO spawned: 'gematik' with pid 81
gematik-server-6559dd79b8-xvwwk gematik-server     Finished dev [unoptimized + debuginfo] target(s) in 0.18s
```

If I create a new node with IPV6 it startes without a problem. 

Maybe you can remove this behaviour? I think at the moment nobody will use IPV6 addresses.

Best regards

Oli

**Comment by Gematik-Entwicklung** [comment]
Hi Oli,

you can change the address the server is listen to by adding the "-l" or "--listen" parameter to the command line. The default value for this parameter is "[::]:3000" to listen to all IPv4 and IPv6 addresses on port 3000. Can you try if the problem still exsists if you pass something like "-l 0.0.0.0:3000"? Thanks.

Best regards,
gematik Dev-Team.

**Comment by nauni77** [comment]
Hello, 
thanks very much for your hint. Add this as argument worked - now only IPV4 is used.

Because of me you can close this issue.

Best regards, Oli
