### ISSUE TITLE
Sorting of audit event request breaks XML format

### ISSUE THREAD

**Issue by carschu** [gematik/ref-eRp-FD-Server#19]
Hello,
requesting sorted audit events contains char "&" which is not encoded and produce an error in XML parser.

Request  https://{{host}}/AuditEvent?_sort=-date
Response
```
<Bundle xmlns="http://hl7.org/fhir">
    <type value="searchset"/>
    <total value="270"/>
    <link>
        <relation value="self"/>
        <url value="/AuditEvent?_sort=-date&pageId=0"/>
    </link>
...
```
The JSON format does not have this problem. Our workaround is to encode it before parsing it.
Bye
  Carsten

**Comment by Gematik-Entwicklung** [comment]
Hi Carsten,

Thanks for the report. We will address this issue in the v0.14.0 release.

Best regards,
gematik Dev-Team.
