### ISSUE TITLE
Need help with generting token files 

### ISSUE THREAD

**Issue by banne01** [gematik/ref-eRp-FD-Server#2]
root@030ff49906e5:/ref-eRp-FD-Server#  cargo run -p ref-erx-fd-server -- --key example.com.key --cert example.com.pem --token  file://ref-eRp-FD-Server/ec1.pem
    Finished dev [unoptimized + debuginfo] target(s) in 0.09s
     Running `target/debug/ref-erx-fd-server --key example.com.key --cert example.com.pem --token 'file://ref-eRp-FD-Server/ec1.pem'`
Error: ServiceError(OpenSslError(ErrorStack([Error { code: 101200014, library: "digital envelope routines", function: "EVP_PKEY_get0_EC_KEY", reason: "expecting a ec key", file: "../crypto/evp/p_lib.c", line: 524 }])))

Can you please document how to generate the token file ? any particular algorithm expected ?

**Comment by Gematik-Entwicklung** [comment]
Hello @banne01 

The service needs two key pairs to operate correctly:

- FD keypair - key pair for the FD service
- IDP keypair - key pair of the IDP service to generate access tokens (this is only for testing purposes, the actual access tokens are generated by the IDP service in the future).

We use elliptic curve cryptography but the algorithms used in this example may change in the future.

To generate the needed key you can use the following Open SSL commands:
```bash
# Generate private key for the service
$ openssl ecparam -name brainpoolP256r1 -genkey -noout -out fd_id

# Extract public key
$ openssl pkey -in fd_id -out fd_id.pub -pubout

# Create X509 certificate
$ openssl req -new -key fd_id > cert.csr
$ openssl x509 -in cert.csr -out fd.cert -req -signkey fd_id -days 1001

# Generate private key for the IDP service (only used for access token generation)
$ openssl ecparam -name prime256v1 -genkey -noout -out idp_id

# Extract public key
$ openssl pkey -in idp_id -out idp_id.pub -pubout
```

After you have generated the keys, you can run the service with the following command:
```bash
$ cargo run -p ref-erx-fd-server -- \
    --key ./path/to/fd_id \
    --cert ./path/to/fd.cert \
    --token file://path/to/idp_id.pub
```

You can than use the official [JWT tool](https://jwt.io/) to generate a ES256 access token with the generated IDP key pair and the following claims:
```json
{
    "acr": "1",
    "aud": "https://erp.telematik.de/login",
    "exp": 2524608000,
    "family_name": "Mustermann",
    "given_name": "Max",
    "iat": 1585336956,
    "idNummer": "X123456789",
    "iss": "https://idp1.telematik.de/jwt",
    "jti": "<IDP>_01234567890123456789",
    "nbf": 1585336956,
    "nonce": "fuu bar baz",
    "organizationName": "Institutions- oder Organisations-Bezeichnung",
    "professionOID": "1.2.276.0.76.4.49",
    "sub": "fIAmb6DtUWgeFCZ1ISKARFmyodOu6UYafXpgwPYtMeNC"
}
```

The access token is used to authenticate you as a user of the service. For more details on the access token please refere to the [offical specification (gemSpec_IDP_FD)](https://fachportal.gematik.de/spezifikationen/online-produktivbetrieb/konzepte-und-spezifikationen/)
