### ISSUE TITLE
Problem with version 0.13.0: Getting error "PukTokenError" - "Expecting: CERTIFICATE"

### ISSUE THREAD

**Issue by carschu** [gematik/ref-eRp-FD-Server#20]
Hello,
the new version 0.13.0 stops during start up with the error:
```
Error: PukTokenError(OpenSslError(ErrorStack([Error { code: 151584876, library: "PEM routines", function: "get_name", reason: "no start line", file: "../crypto/pem/pem_lib.c", line: 745, data: "Expecting: CERTIFICATE" }])))
```
From the committed changes in the REAME file I saw that you mention to generate a certificate to file "idp_id.cert". But I don't see an instruction to use this new certificate. So I changed the parameter "token" in the startup command:
```
--token file://path/to/idp_id.cert
```
Is this the right way to fix the error?
Bye
  Carsten

**Comment by Gematik-Entwicklung** [comment]
Hi Carsten,

you are right, the service now expects a certificate in the `--token` parameter. We missed to update the command line parameters in the readme. We will fix that.

Best regards,
gematik Dev-Team.
