### ISSUE TITLE
ref-eRp-FD-Server

### ISSUE THREAD

**Issue by stefankranz** [gematik/ref-eRp-FD-Server#24]
Hi there,

Can you describe this service better? Is it a test server? Or is it a middleware to address the Gematik infrastructure?

Regards,
Stefan

**Comment by hattenbach** [comment]
Hi Stefan, it's a reference implementation, so more a test/mock. It aims to comply to the spec as linked in its readme; neither for production use nor a middleware to connect to TI. Any suggestions how and where we should add precision to the description?

**Comment by stefankranz** [comment]
Cool, we have a look on it. Where i can find test certs and user credentials ? Or we need a contract to test ?

**Comment by pandalec** [comment]
Hi Stefan,

Maybe you should start to read the README.md file? It is everything described in there.

BR
parsi
