### ISSUE TITLE
with 0.14.0 activate fails

### ISSUE THREAD

**Issue by nauni77** [gematik/ref-eRp-FD-Server#25]
Hello,

now I upgraded to release tag 0.14.0. The build works fine, but I always got an exception activating an eprescription. I did the following steps. The attached ZIP file contains all files to show the execution commands, the generated helper files and the output of the command. The order is:

1. 01-createEprescription_cmd.txt
  => command
2. 02-createEprescription_stdout.json
  => output of command createEprescription
3. 03-eRezept_PZN_1_bundle.xml
  => helper file
4. 04-signEprescription_cmd.txt
  => sign this eprescription bundle from 3.
5. 05-signEprescription_stdout.txt
  => output of command 4
6. 01-activate_parameters.json
  => create the json file with content of signed eprescription (step 05)
7. 02-activate_cmd.txt
  => command for activating eprescription
8. 03-activate_stdout.json
  => output of 7. => error message of activating

I think it's easier to look into the files - insteed of copy the complete content into this issue.

The execution of these commands are completely automated and it works with 0.13.0 perfect. But it fails with 0.14.0.

Hope you can help me.

Best regards, Oli
[160.000.720.084.300.13.zip](https://github.com/gematik/ref-eRp-FD-Server/files/6203968/160.000.720.084.300.13.zip)

**Comment by nauni77** [comment]
Idear: Maybe you don't support JSON anymore inside the body of the POST request of activation? Because at error message you write: "Error while decodeing XML: ...".

**Comment by Gematik-Entwicklung** [comment]
Hi Oli,

in release 0.14.0 we've updated the KBV profile to the latest version (1.0.1) and your request contains the KBV profile version 1.0.0. If you update your KBV Bundle to the current version of the profile, it should work.

You can find an example of the updated bundle in [server\examples\kbv_bundle.xml](../blob/master/server/examples/kbv_bundle.xml).

Best regards,
gematik Dev-Team.

**Comment by nauni77** [comment]
Hello, 
thanks for your note! It works.

It would be great to write in future such an important information into the ReleaseNotes.md . I think the most people who use your software will just compile and use your test environment. It would be great to get a short info about the needed changes to make the new release work.

Best regards, Oli
