### ISSUE TITLE
this infrastructure is mandatory for third vendors 

### ISSUE THREAD

**Issue by tommyyama2020** [gematik/ref-eRp-FD-Server#30]
Hello, 

This might not be an issue particularly. 

However, this infrastructure is mandatory to develop Healthcare IT products including e-prescription feature for German healthcare users in Germany ?

**Comment by lieven-dev** [comment]
Hi tommyyama2020,

no, this is not mandatory. It is a reference implementation for bootstraping e-Rezept in germany. This project will be archived and will no longer be maintained as the e-Rezept is already in production and running. 

Best regards,
gematik Dev-Team.
