### ISSUE TITLE
Error when using tool for creating access tokens with claims_patient.json

### ISSUE THREAD

**Issue by pandalec** [gematik/ref-eRp-FD-Server#5]
Hey!

Using the new tool for creating an access token like mentioned in the docs results in error: `Access Token Error: Invalid profession!!`
The access token is created with `server/examples/claims_patient.json`. Using a new claims.json with similar content and change `professionOID` to `1.2.276.0.76.4.30` (oid_arzt) access is working properly. Don't know if this an error or happens on purpose. 

Best regards,
parsi

**Comment by Gematik-Entwicklung** [comment]
Hi @parsifallo,

the readme is a bit missleading here, we will clearify that. In general, an ACCESS_TOKEN enables the user of the service to execute different operations. The provided example generates a ACCESS_TOKEN for a Patient but patients are not allowed to create or activate Tasks, which is shown in the other examples. To successfully execute the other examples, you need a ACCESS_TOKEN with a different profession, as you already noticed.

Best regards,
gematik Dev-Team.

**Comment by pandalec** [comment]
Hi dev Team,
ok great, thank you again for your quick response!
BR,
parsi
