### ISSUE TITLE
Cannot get task $activate to work

### ISSUE THREAD

**Issue by pandalec** [gematik/ref-eRp-FD-Server#8]
Hey Dev Team!

I am trying to activate the TaskID for an ePrescription. First I used a RU Konnektor and tried to sign the ePrescription with an "Heilberufsausweis" (HBA). Signing is not a problem but the ref-eRp-FD-Server won't acknowledge the certificate from the HBA. Error message:
`OpenSSL Error: error:21075075:PKCS7 routines:PKCS7_verify:certificate verify error:../crypto/pkcs7/pk7_smime.c:284:Verify error:unable to get local issuer certificate`

I am no Rust developer but I tried to have a look into the code and how openssl is used inside ref-eRp-FD-Server. For me it seems that it sticks to local/self-signed certificates and won't use global or other certificates than its own. I played around with another TSL.xml or switched the `--qes-cert` parameter to the certificate from the HBA. But no success.

So I used the new provided tool for generating the signature/ePrescription bundle with the self-signed certificate like described in the documentation. Now my error is different:
`OpenSSL Error: error:21075075:PKCS7 routines:PKCS7_verify:certificate verify error:../crypto/pkcs7/pk7_smime.c:284:Verify error:self signed certificate`

For me it looks like that the self signed certificate won't work and for self-signed certificates the openssl parameter `-noverify` is missing, please correct me if I am wrong.

So my questions are:
Has anyone tested ref-eRp-FD-Server inside the RU against a Konnektor and is it possible with the current state of the server application?
How can I get the server to acknowledge certificates from an HBA?
And last but not least, why do I get a verification error for self-signed certificates?

Best regards,
parsi

**Comment by Gematik-Entwicklung** [comment]
Hi @parsifallo,

using signed ePrescriptions from the Konnektor is not supported now. In the current state we only fetch and prepare the TSL for the next steps. Currently the TSL is not used to verify other certificats or certificate chains. Therefore we added the "qes-cert" parameter, that user can pass their own certificates to verify the QES Containers.

The error message from openssl is a bit missleading here. We currently pass the qes certificate from the command line argument to the opernssl verify method. If the certificate within the QES container can not be verified against the passed certificate it is interpreted as "self-signed" and the operation will fail. If you pass the "no verify" parameter to the openssl verify method you should get a verify error, because your certificates does not match.

I've tested the whole workflow to create and active a new task. Please refere to the commands below, I hope this will help you :)

Best regards,
gematik Dev-Team.

````console
# HINT: Please make sure you use the ACCESS_TOKEN, Task ID and Task ACCESS_CODE generated by your commands!

# Create Needed Credentials
openssl ecparam -name brainpoolP256r1 -genkey -noout -out fd_id
openssl pkey -in fd_id -out fd_id.pub -pubout
openssl req -new -key fd_id > cert.csr
openssl x509 -in cert.csr -out fd.cert -req -signkey fd_id -days 1001
openssl ecparam -name brainpoolP256r1 -genkey -noout -out qes_id
openssl pkey -in qes_id -out qes_id.pub -pubout
openssl req -new -key qes_id > cert.csr
openssl x509 -in cert.csr -out qes.cert -req -signkey qes_id -days 1001
openssl ecparam -name brainpoolP256r1 -genkey -noout -out idp_id
openssl pkey -in idp_id -out idp_id.pub -pubout

# Start the Service
cargo run -p ref-erx-fd-server -- \
    --key fd_id \
    --cert fd.cert \
    --qes-cert qes.cert \
    --token file://./idp_id.pub \
    --tsl https://download.tsl.ti-dienste.de

# Create ACCESS_TOKEN
sed 's/1.2.276.0.76.4.49/1.2.276.0.76.4.30/g' server/examples/claims_patient.json > claims_arzt.json
cargo run -p tool -- \
    create-access-token \
        --key idp_id \
        --claims claims_arzt.json

# Create Task
curl \
    --data-binary @server/examples/task_create_parameters.json \
    --header "Content-Type: application/fhir+json" \
    --header "Authorization: Bearer eyJhbGciOiJCUDI1NlIxIiwieDVjIjpbXX0.eyJhY3IiOiJlaWRhcy1sb2EtaGlnaCIsImF1ZCI6Imh0dHBzOi8vZXJwLnRlbGVtYXRpay5kZS9sb2dpbiIsImV4cCI6MjUyNDYwODAwMCwiZmFtaWx5X25hbWUiOiJkZXIgTmFjaG5hbWUiLCJnaXZlbl9uYW1lIjoiZGVyIFZvcm5hbWUiLCJpYXQiOjE1ODUzMzY5NTYsImlkTnVtbWVyIjoiWDIzNDU2Nzg5MCIsImlzcyI6Imh0dHBzOi8vaWRwMS50ZWxlbWF0aWsuZGUvand0IiwianRpIjoiPElEUD5fMDEyMzQ1Njc4OTAxMjM0NTY3ODkiLCJuYmYiOjE1ODUzMzY5NTYsIm5vbmNlIjoiZnV1IGJhciBiYXoiLCJvcmdhbml6YXRpb25OYW1lIjoiSW5zdGl0dXRpb25zLSBvZGVyIE9yZ2FuaXNhdGlvbnMtQmV6ZWljaG51bmciLCJwcm9mZXNzaW9uT0lEIjoiMS4yLjI3Ni4wLjc2LjQuMzAiLCJzdWIiOiJSYWJjVVN1dVdLS1pFRUhtcmNObV9rVURPVzEzdWFHVTVaazhPb0J3aU5rIn0.RVzDrJq5Trb6hI0ajpVBomnYInMCXlpICZk7AgOqsnoImXtB-lWRaMVqwoLCdpp3CRX07iF8D5C4k5oPnjLFuQ  " \
    --output task1.json \
    'http://localhost:3000/Task/$create'

# Create QES Container from KBV Bundle
cargo run -p tool -- \
    pkcs7-sign \
        --key qes_id \
        --cert qes.cert \
        --input server/examples/kbv_bundle.xml \
        --output kbv_bundle.qes

# Create Task Activate Parameters
qes=$(cat kbv_bundle.qes \
| sed 's/-----.*-----//g' \
| sed ':a;N;$!ba;s/\n//g' \
| sed '/^$/d'); \
qes="\"data\":\"$qes\""; \
echo "$qes" | sed \
    '/"data":".*"/{
        r /dev/stdin
        d
        }' \
    server/examples/task_activate_parameters.json \
    > task_activate_parameters.json

# Activate the Task
curl \
    --data-binary @task_activate_parameters.json \
    --header "Content-Type: application/fhir+json" \
    --header "Authorization: Bearer eyJhbGciOiJCUDI1NlIxIiwieDVjIjpbXX0.eyJhY3IiOiJlaWRhcy1sb2EtaGlnaCIsImF1ZCI6Imh0dHBzOi8vZXJwLnRlbGVtYXRpay5kZS9sb2dpbiIsImV4cCI6MjUyNDYwODAwMCwiZmFtaWx5X25hbWUiOiJkZXIgTmFjaG5hbWUiLCJnaXZlbl9uYW1lIjoiZGVyIFZvcm5hbWUiLCJpYXQiOjE1ODUzMzY5NTYsImlkTnVtbWVyIjoiWDIzNDU2Nzg5MCIsImlzcyI6Imh0dHBzOi8vaWRwMS50ZWxlbWF0aWsuZGUvand0IiwianRpIjoiPElEUD5fMDEyMzQ1Njc4OTAxMjM0NTY3ODkiLCJuYmYiOjE1ODUzMzY5NTYsIm5vbmNlIjoiZnV1IGJhciBiYXoiLCJvcmdhbml6YXRpb25OYW1lIjoiSW5zdGl0dXRpb25zLSBvZGVyIE9yZ2FuaXNhdGlvbnMtQmV6ZWljaG51bmciLCJwcm9mZXNzaW9uT0lEIjoiMS4yLjI3Ni4wLjc2LjQuMzAiLCJzdWIiOiJSYWJjVVN1dVdLS1pFRUhtcmNObV9rVURPVzEzdWFHVTVaazhPb0J3aU5rIn0.RVzDrJq5Trb6hI0ajpVBomnYInMCXlpICZk7AgOqsnoImXtB-lWRaMVqwoLCdpp3CRX07iF8D5C4k5oPnjLFuQ  " \
    --header "X-AccessCode: BA5C94000B942AC4841B808C3C5429CC3875E7162DCF69DE29616FAB7672" \
    --output task2.json \
    'http://localhost:3000/Task/13814004-1dd2-11b2-802a-109eee73030e/$activate'

**Comment by pandalec** [comment]
Thank you very much! I will give this a try and give feedback afterwards :)

**Comment by pandalec** [comment]
Works for me. Thank you!
