### ISSUE TITLE
Cannot get "E-Rezept abrufen" to work

### ISSUE THREAD

**Issue by pandalec** [gematik/ref-eRp-FD-Server#9]
Hey ho!

I've got a problem with the task to get the ePrescription secret, which would be handled by a pharmacy.

Here's a log what I do:
```
2020-11-25T14:05:19.038118+01:00 INFO access_log - HTTP/1.1 POST - [::1]:59608 - /Task/$create
2020-11-25T14:05:19.508416+01:00 INFO access_log - HTTP/1.1 POST - [::1]:59609 - /Task/13814003-1dd2-11b2-802a-28e2663c469f/$activate
```
outcome here is:
```
authoredOn: 2020-11-25T14:05:19.039918+01:00
for.identifier.value: X234567890
id: 13814003-1dd2-11b2-802a-28e2663c469f
intent: order
lastModified: 2020-11-25T14:05:19.040201+01:00
resourceType: Task
status: ready
```

Now I want the task information and I receive it with:
`2020-11-25T14:06:27.191586+01:00 INFO access_log - HTTP/1.1 GET - [::1]:59624 - /Task`

outcome here:
```
ID: 13814003-1dd2-11b2-802a-28e2663c469f
PrescriptionID: 160.000.000.000.123.76
AccessCode: D27FF2F86026573B14CE89C913C6FE8C1C67A8F17E574CF1F4C9B1CA6FFD498
authoredOn: 11/25/2020 14:05:19
status: ready
```

Now I have every information I need for "handing over" the task to a pharmacy as 2d code or what ever:
`{ "urls": [ "Task/13814003-1dd2-11b2-802a-28e2663c469f/$accept?ac=D27FF2F86026573B14CE89C913C6FE8C1C67A8F17E574CF1F4C9B1CA6FFD498" ] } `

But now the result of the following 
`2020-11-25T14:07:18.767041+01:00 INFO access_log - HTTP/1.1 POST - [::1]:59634 - /Task/13814003-1dd2-11b2-802a-28e2663c469f/$accept?ac=D27FF2F86026573B14CE89C913C6FE8C1C67A8F17E574CF1F4C9B1CA6FFD498`
is
`"StatusCode: NotFound, Content-Type: , Content-Length: 0)"`

Any idea what I am doing wrong?

**Comment by Gematik-Entwicklung** [comment]
Hi @parsifallo,

the Task $accept operation is not yet implemented. It is scheduled in our next sprint, so it should be done in the next release v0.8.0 on 09.12.2020.

Best regards,
gematik Dev-Team.

**Comment by Gematik-Entwicklung** [comment]
Hi @parsifallo,

the Task $accept operation is now available. Please refere to the latest release (v0.8.0).

Best regards,
gematik Dev-Team.
